name: Build and Push Docker

on:
  push:
    branches:
      - sse-redis

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chatmed-0320
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 'lts/*'

      # - name: Install Dependencies
      #   run: npm install

      - name: Rename package-lock file
        run: mv package-lock.vercel.json package-lock.json

      - name: Build Docker Image
        run: docker build -t ttl.sh/${{ env.IMAGE_NAME }}:1h .

      - name: Push Docker Image to ttl.sh
        run: |
          # echo ${{ secrets.TTL_SH_TOKEN }} | docker login ttl.sh -u ${{ secrets.TTL_SH_USERNAME }} --password-stdin
          docker push ttl.sh/${{ env.IMAGE_NAME }}:1h
