name: Build and Push Docker
# ref https://www.hyperxiao.top/zh-CN/posts/5
on:
  push:
    branches:
      - sse-redis

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chatmed
      HUB: uhub.service.ucloud.cn
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     # !! 删除腾讯云repo下的package-lock.json
      - name: remove package-lock file 
        run: rm package-lock*

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run:  npm install

      # 构建和导出静态文件
      - name: Build and Export Next.js App
        run: |
          npm run build
          npm run export -o /tmp/nextjs_out

      # 将静态文件上传到GitHub Artifacts
      - name: Upload Static Files
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-static-files
          path: /tmp/nextjs_out

      - name: create env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          envkey_OPENAI_ASSISTANT_ID: ${{secrets.OPENAI_ASSISTANT_ID}}
          envkey_HELICONE_API_KEY: ${{secrets.HELICONE_API_KEY}}

      # 登录至registry
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HUB }}
          username: ${{ secrets.UCLOUD_USERNAME }}
          password: ${{ secrets.UCLOUD_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.HUB }}/${{secrets.UCLOUD_REPO}}/${{ env.IMAGE_NAME }}:latest
